---
AWSTemplateFormatVersion: '2010-09-09'

#  __       ______    ______    ______   ______  __    __   ______         _______   __    __   ______   __    __  ________ ________ 
# |  \     /      \  /      \  /      \ |      \|  \  |  \ /      \       |       \ |  \  |  \ /      \ |  \  /  \|        \        \
# | $$    |  $$$$$$\|  $$$$$$\|  $$$$$$\ \$$$$$$| $$\ | $$|  $$$$$$\      | $$$$$$$\| $$  | $$|  $$$$$$\| $$ /  $$| $$$$$$$$\$$$$$$$$
# | $$    | $$  | $$| $$ __\$$| $$ __\$$  | $$  | $$$\| $$| $$ __\$$      | $$__/ $$| $$  | $$| $$   \$$| $$/  $$ | $$__      | $$   
# | $$    | $$  | $$| $$|    \| $$|    \  | $$  | $$$$\ $$| $$|    \      | $$    $$| $$  | $$| $$      | $$  $$  | $$  \     | $$   
# | $$    | $$  | $$| $$ \$$$$| $$ \$$$$  | $$  | $$\$$ $$| $$ \$$$$      | $$$$$$$\| $$  | $$| $$   __ | $$$$$\  | $$$$$     | $$   
# | $$____| $$__/ $$| $$__| $$| $$__| $$ _| $$_ | $$ \$$$$| $$__| $$      | $$__/ $$| $$__/ $$| $$__/  \| $$ \$$\ | $$_____   | $$   
# | $$     \$$    $$ \$$    $$ \$$    $$|   $$ \| $$  \$$$ \$$    $$      | $$    $$ \$$    $$ \$$    $$| $$  \$$\| $$     \  | $$   
#  \$$$$$$$$\$$$$$$   \$$$$$$   \$$$$$$  \$$$$$$ \$$   \$$  \$$$$$$        \$$$$$$$   \$$$$$$   \$$$$$$  \$$   \$$ \$$$$$$$$   \$$   
                                                                                                                                   

Description: |
  An S3 Bucket that is perfect for logging from a VPC: Flow Logs, ELB Access Logs, etc.

Parameters:

  Prefix:
    Type: String
    Default: demo
    Description: "A Prefix to use on the resource names and exports (To ensure uniqueness)."

Mappings:

  RegionalConfigs:
    # Accounts needed to grant access for ELB access logging
    # as per: https://docs.aws.amazon.com/elasticloadbalancing/latest/application/enable-access-logging.html
    us-east-1:
      ELBAccountId: '127311923021'
    us-east-2:
      ELBAccountId: '033677994240'
    us-west-2:
      ELBAccountId: '797873946194'
    ca-central-1:
      ELBAccountId: '985666609251'

Resources:

  # KMS Key for S3 bucket encryption
  BucketKey:
    Type: 'AWS::KMS::Key'
    Properties:
      Description: !Sub 
        - 'Symmetric encryption key for ${Prefix} logging bucket.'
        - Prefix: !Ref Prefix
      EnableKeyRotation: true
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
        - Sid: Root
          Effect: Allow
          Action: 'kms:*'
          Resource: '*'
          Principal:
            AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
        
        # For FLow Logs
        # https://docs.aws.amazon.com/vpc/latest/tgw/flow-logs-s3.html#flow-logs-s3-cmk-policy
        - Sid: AllowVPCFlowLogs
          Effect: Allow
          Principal:
            Service:
              - delivery.logs.amazonaws.com
          Action:
            - 'kms:Encrypt'
            - 'kms:Decrypt'
            - 'kms:ReEncrypt*'
            - 'kms:GenerateDataKey*'
            - 'kms:DescribeKey'
          Resource: '*'
        
        # For ELB access logs 
        - Sid: "ELBAccessLogsPut"
          Effect: Allow
          Action:
            - 'kms:Encrypt'
            - 'kms:Decrypt'
            - 'kms:ReEncrypt*'
            - 'kms:GenerateDataKey*'
            - 'kms:DescribeKey'
          Resource: '*'
          Principal:
            AWS: !Join
              - ''
              - - 'arn:aws:iam::'
                - !FindInMap [ "RegionalConfigs", !Ref "AWS::Region", "ELBAccountId"]
                - ':root'

      Tags:
        - Key: demo
          Value: !Ref Prefix
        - Key: notes
          Value: "Used to encrypt S3 logging bucket"

  # Create an Alias so the Key is easy to find in the console. 
  BucketKeyAlias:
    Type: AWS::KMS::Alias
    Properties: 
      AliasName: !Sub 
        # Don't remove the alias part - required!
        - 'alias/logging-bucket-key-${Prefix}'
        - Prefix: !Ref Prefix
      TargetKeyId: !Ref BucketKey

  # The Logging Bucket. We don't name this - easier to let CFN pick the name (for uniqueness!)
  LoggingBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - BucketKeyEnabled: true
            ServerSideEncryptionByDefault:
              SSEAlgorithm: 'aws:kms'
              KMSMasterKeyID: !GetAtt BucketKey.Arn
      Tags:
        - Key: demo
          Value: !Ref Prefix
        - Key: notes
          Value: "Bucket for VPC Flow logs and other logging"
          
  LoggingBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties: 
      Bucket: !Ref LoggingBucket
      PolicyDocument:
        Version: 2012-10-17
        
         # Policy for ELB access logs 
         # as per: https://docs.aws.amazon.com/elasticloadbalancing/latest/application/enable-access-logging.html
        Statement:
          - Sid: "ELBAccessLogsPut"
            Effect: Allow
            Action: 's3:PutObject'
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref LoggingBucket
                - '/*'
            Principal:
              AWS: !Join
                - ''
                - - 'arn:aws:iam::'
                  - !FindInMap [ "RegionalConfigs", !Ref "AWS::Region", "ELBAccountId"]
                  - ':root'
            
          # Bucket Policy for VPC Flow Logs, as per:
          # https://docs.aws.amazon.com/vpc/latest/userguide/flow-logs-s3.html#flow-logs-s3-permissions 
          # https://docs.aws.amazon.com/vpc/latest/userguide/flow-logs-s3.html#flow-logs-s3-iam
          - Sid: AWSFlowLogDeliveryWrite
            Effect: Allow
            Action: 's3:PutObject'
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref LoggingBucket
                - '/*'
            Principal:
              Service: "delivery.logs.amazonaws.com"
            Condition:
              # These are a best practice to prevent the Confused Deputy Problem
              # https://docs.aws.amazon.com/IAM/latest/UserGuide/confused-deputy.html
              StringEquals:
                'aws:SourceAccount': !Ref "AWS::AccountId"
                's3:x-amz-acl': "bucket-owner-full-control"
              ArnLike:
                "aws:SourceArn": !Join
                  - ":"
                  - - "arn:aws:logs"
                    - !Ref "AWS::Region"
                    - !Ref "AWS::AccountId"
                    - "*"
                    
          - Sid: AWSFlowLogDeliveryAclCheck
            Action: 's3:GetBucketAcl'
            Effect: Allow
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref LoggingBucket
            Principal:
              Service: "delivery.logs.amazonaws.com"
            Condition:
              StringEquals:
                'aws:SourceAccount': !Ref "AWS::AccountId"
              ArnLike:
                'aws:SourceArn': !Join
                  - ":"
                  - - "arn:aws:logs"
                    - !Ref "AWS::Region"
                    - !Ref "AWS::AccountId"
                    - "*"
                    
          # No HTTP allowed!  (Certain services like S3, SQS, DynamoDB support HTTP!)
          - Sid: DenyInsecureConnections
            Effect: Deny
            Principal: '*'
            Action: 's3:*'
            Resource: !Join 
              - ''
              - - !GetAtt 
                  - LoggingBucket
                  - Arn
                - "/*"
            Condition:
              Bool:
                'aws:SecureTransport': false

Outputs:

  LoggingBucket:
    Description: This is the bucket Name. Where the vpc flow logs and other logs (elb access logs) etc. can go.
    Value: !Ref LoggingBucket
    Export:
      Name: !Join ['-', [ !Ref Prefix, 'VPCLoggingBucket']]

  LoggingBucketArn:
    Description: This is the bucket Arn. Where the vpc flow logs and other logs (elb access logs) etc. can go.
    Value: !GetAtt LoggingBucket.Arn
    Export:
      Name: !Join ['-', [ !Ref Prefix, 'VPCLoggingBucketArn']]
