---
AWSTemplateFormatVersion: '2010-09-09'
  
Description: |
  super-vpc : Transit Gateway

Parameters:

  Prefix:
    Type: String
    Default: demo
    Description: "A Prefix to use on the resource names and exports (To ensure uniqueness). For example, the VPC will be named: demo-vpc"

  ASN:
    Type: Number
    Default: 64512
    Description: "An Autonomous System Number (ASN) that must be unique. Range is 64512 to 65534"

Resources:

  TransitGateway:
    Type: "AWS::EC2::TransitGateway"
    Properties:
      AmazonSideAsn: !Ref ASN
      Description: !Ref Prefix
      AutoAcceptSharedAttachments: "disable"
      DefaultRouteTableAssociation: "enable"
      DnsSupport: "enable"
      Tags:
      - Key: Name
        Value: !Ref Prefix
      - Key: demo
        Value: "super-vpc"

Outputs:
      
  TgwId:
    Description: The TGW Id
    Value: !Ref TransitGateway
    Export:
      Name: !Join ["-", [ !Ref Prefix, "TgwId"]]
